filestorage:
    file:
        #the parent path of the file storage directory
        basePath: E:/programs/fileTests
        #the maximum size of the files uploaded, expressed in bytes
        uploadMaxSize: 1048576
        #how many entries should the search API bring in one call
        pageSize: 20
server:
    servlet:
        context-path: /filestorage
spring:
    servlet:
        multipart:
            enabled: true
            maxFileSize: -1
            maxRequestSize: -1
